### ISSUE TITLE
print_yaks encoding error

### ISSUE THREAD

**Issue by whaatt** [jaredmichaelsmith/pyak#4]
Hi there! First of all, this library is really awesome and will help a bunch with a research project I'm doing this semester, so if you'd like any help in making it better/keeping it up-to-date with the YikYak private API, just let me know.

Just a small issue I encountered when running print_yaks on Windows:
`Traceback (most recent call last):
  File "print_yaks.py", line 26, in <module>
    yak.print_yak()
  File "C:\Users\Sanjay\Downloads\pyak-master\pyak\pyak.py", line 148, in print_yak
    print self.message
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 25-42: character maps to <undefined>`

I'm guessing it's an encoding issue with the way this handles printing emojis, possibly? In any case, the fix was to `import sys` and change `print self.message` to `print self.message.encode(sys.stdout.encoding, errors='replace')` (which suppresses those errors).

**Comment by jaredmichaelsmith** [comment]
Thanks for your contribution! 

I haven't really had the time to maintain this, but I am welcome to giving you commit access if you want to help and make regular updates to the code and revising as per Yik Yak's Private API changes.

Given the interest I have had in this, I will try to work on it more.

And regarding the issue, I would rather enable the code to deal properly with any characters received from YY's API, so maybe we can update it to properly handle the extraneous cases.

**Comment by whaatt** [comment]
I'd love to pitch in and would definitely appreciate commit access. Mostly
I'll make minor fixes as I find them, and run anything even moderately
significant by you first. Let me know!

2015-09-30 20:54 GMT-07:00 Jared Smith <notifications@github.com>:

**Comment by jaredmichaelsmith** [comment]
Okay, sweet! I will give you those permissions. Be sure to tell your friends and colleagues about this so hopefully more people are aware of it! YY is an amazing data source and I hate to see it go to waste into a proprietary trash bin.

Also, you should check out the latest version of the repo, I turned it all into a Python package and cleaned up some stuff.
